# ██████╗ ██████╗ ███████╗██╗    ██╗███████╗██╗██╗     ███████╗
# ██╔══██╗██╔══██╗██╔════╝██║    ██║██╔════╝██║██║     ██╔════╝
# ██████╔╝██████╔╝█████╗  ██║ █╗ ██║█████╗  ██║██║     █████╗
# ██╔══██╗██╔══██╗██╔══╝  ██║███╗██║██╔══╝  ██║██║     ██╔══╝
# ██████╔╝██║  ██║███████╗╚███╔███╔╝██║     ██║███████╗███████╗
# ╚═════╝ ╚═╝  ╚═╝╚══════╝ ╚══╝╚══╝ ╚═╝     ╚═╝╚══════╝╚══════╝

tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/services"

brew "curl"
brew "exa"
brew "git"
brew "git-lfs"
brew "jq"
brew "wget"
brew "tree"
